USE codeup_test_db;

INSERT INTO albums (artist, name, release_date, genre, sales)
VALUES
    ('Michael Jackson', 'Thriller', 1982, 'Pop, Rock, R&B', 47.3),
    ('Eagles', 'Their Greatest Hits (1971-1975', 1976, 'Country Rock, Soft Rock, folk Rock', 41.2),
    ('AC/DC', 'Back in Black', 1980, 'Hard Rock', 24.2),
    ('Pink Floyd', 'The Dark Side of the Moon', 1973, 'Progressive Rock', 24.2),
    ('Whitney Houston / Various Artists', 'The Bodyguard', 1992, 'R&B, Soul, Pop, Soundtrack', 28.4),
    ('Meat Loaf', 'Bat Out of Hell', 1977, 'Hard rock, Glam Rock, Heavy Metal', 21.5),
    ('Eagles', 'Hotel California', 1976, 'Soft Rock', 31.5),
    ('Bee Gees / Various Artists', 'Saturday Night Fever', 1977, 'Disco', 21.6),
    ('Fleetwood Mac', 'Rumours', 1977, 'Soft Rock', 27.9),
    ('Shania Twain', 'Come On Over', 1997, 'Country, Pop', 29.6),
    ('Various Artists', 'Grease: The Original Soundtrack from the Motion Picture', 1978, 'Rock and Roll', 14.4),
    ('Led Zeppelin', 'Led Zeppelin IV', 1971, 'Hard Rock, Heavy Metal, Folk Rock', 29.0),
    ('Michael Jackson', 'Bad', 1987, 'Pop, Funk, Rock', 19.3),
    ('Alanis Morisette', 'Jagged Little Pill', 1995, 'Alternative Rock', 24.4),
    ('Celine Dion', 'Falling Into You', 1996, 'Pop, Soft Rock', 20.2),
    ('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', 1967, 'Rock', 18.2),
    ('Various Artists', 'Dirty Dancing', 1987, 'Pop, Rock, R&B', 17.9),
    ('Michael Jackson', 'Dangerous', 1991, 'Rock, Funk, Pop', 17.3),
    ('Adele', '21', 2011, 'Pop, Soul', 25.3),
    ('Celine Dion', 'Let''s Talk About Love', 1997, 'Pop, Soft Rock', 19.3),
    ('The Beatles', '1', 2000, 'Rock', 23.4),
    ('ABBA', 'Gold: Greatest Hits', 1992, 'Pop, Disco', 23.0),
    ('Madonna', 'The Immaculate Collection', 1990, 'Pop, Dance', 19.4),
    ('The Beatles', 'Abbey Road', 1969, 'Rock', 14.4),
    ('Bruce Springsteen', 'Born in the USA', 1984, 'Heartland Rock', 19.6),
    ('Dire Straits', 'Brothers in Arms', 1985, 'Roots Rock, Blues Rock, Soft Rock', 17.7),
    ('James Horner', 'Titanic: Music from the Motion Picture', 1997, 'Film Score', 18.1),
    ('Metallica', 'Metallica', 1991, 'Heavy Metal', 25.2),
    ('Nirvana', 'Nevermind', 1991, 'Grunge, Alternative Rock', 16.7),
    ('Pink Floyd', 'The Wall', 1979, 'Progressive Rock', 18.7),
    ('Santana', 'Supernatural', 1999, 'Latin Rock', 20.5),
    ('Guns N'' Roses', 'Appetite for Destruction', 1987, 'Hard Rock', 21.6);